repos:
  - repo: local
    hooks:
      - id: add-license-header
        name: Add Apache License header
        entry: python scripts/add_license_header.py
        language: python
        stages: [pre-commit]
